name: Run tests

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.7"
      - uses: julia-actions/julia-buildpkg@master
      - uses: julia-actions/julia-runtest@master